// This file is auto-generated by @hey-api/openapi-ts

export const Body_coaches_create_coachSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        photo: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo'
        }
    },
    type: 'object',
    required: ['name', 'role'],
    title: 'Body_coaches-create_coach'
} as const;

export const Body_coaches_update_coachSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        photo: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo'
        }
    },
    type: 'object',
    title: 'Body_coaches-update_coach'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_match_media_upload_match_photoSchema = {
    properties: {
        photo: {
            type: 'string',
            format: 'binary',
            title: 'Photo'
        },
        caption: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption'
        }
    },
    type: 'object',
    required: ['photo'],
    title: 'Body_match-media-upload_match_photo'
} as const;

export const Body_players_create_playerSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        jersey_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Jersey Number'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        has_parental_consent: {
            type: 'boolean',
            title: 'Has Parental Consent',
            default: false
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        photo: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo'
        }
    },
    type: 'object',
    required: ['name', 'first_name'],
    title: 'Body_players-create_player'
} as const;

export const Body_players_update_playerSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        jersey_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Jersey Number'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        has_parental_consent: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Has Parental Consent'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        photo: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo'
        }
    },
    type: 'object',
    title: 'Body_players-update_player'
} as const;

export const CoachPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        role: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Role'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        }
    },
    type: 'object',
    required: ['name', 'role', 'id'],
    title: 'CoachPublic'
} as const;

export const CoachesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CoachPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CoachesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LandingPageDataSchema = {
    properties: {
        upcoming_matches: {
            items: {
                '$ref': '#/components/schemas/MatchPublic'
            },
            type: 'array',
            title: 'Upcoming Matches'
        },
        recent_matches: {
            items: {
                '$ref': '#/components/schemas/MatchPublic'
            },
            type: 'array',
            title: 'Recent Matches'
        },
        team_name: {
            type: 'string',
            title: 'Team Name'
        }
    },
    type: 'object',
    required: ['upcoming_matches', 'recent_matches', 'team_name'],
    title: 'LandingPageData'
} as const;

export const MatchCreateSchema = {
    properties: {
        match_date: {
            type: 'string',
            format: 'date-time',
            title: 'Match Date'
        },
        home_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Home Team'
        },
        away_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Away Team'
        },
        precautions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precautions'
        }
    },
    type: 'object',
    required: ['match_date', 'home_team', 'away_team'],
    title: 'MatchCreate'
} as const;

export const MatchDetailPublicSchema = {
    properties: {
        match_date: {
            type: 'string',
            format: 'date-time',
            title: 'Match Date'
        },
        home_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Home Team'
        },
        away_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Away Team'
        },
        precautions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precautions'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        home_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Home Score'
        },
        away_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Away Score'
        },
        updates: {
            items: {
                '$ref': '#/components/schemas/MatchUpdatePublic'
            },
            type: 'array',
            title: 'Updates',
            default: []
        },
        media: {
            items: {
                '$ref': '#/components/schemas/MatchMediaPublic'
            },
            type: 'array',
            title: 'Media',
            default: []
        }
    },
    type: 'object',
    required: ['match_date', 'home_team', 'away_team', 'id', 'status'],
    title: 'MatchDetailPublic',
    description: 'Match detail including updates and media.'
} as const;

export const MatchMediaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        media_type: {
            type: 'string',
            title: 'Media Type'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        caption: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'media_type'],
    title: 'MatchMediaPublic'
} as const;

export const MatchMediaVideoCreateSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        caption: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'MatchMediaVideoCreate'
} as const;

export const MatchPatchSchema = {
    properties: {
        match_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Date'
        },
        home_team: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Home Team'
        },
        away_team: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Away Team'
        },
        precautions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precautions'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MatchStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        home_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Home Score'
        },
        away_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Away Score'
        }
    },
    type: 'object',
    title: 'MatchPatch',
    description: 'PATCH body for updating a match (named to avoid collision with MatchUpdate table).'
} as const;

export const MatchPublicSchema = {
    properties: {
        match_date: {
            type: 'string',
            format: 'date-time',
            title: 'Match Date'
        },
        home_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Home Team'
        },
        away_team: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Away Team'
        },
        precautions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precautions'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        home_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Home Score'
        },
        away_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Away Score'
        }
    },
    type: 'object',
    required: ['match_date', 'home_team', 'away_team', 'id', 'status'],
    title: 'MatchPublic'
} as const;

export const MatchStatusSchema = {
    type: 'string',
    enum: ['upcoming', 'live', 'completed'],
    title: 'MatchStatus'
} as const;

export const MatchUpdateCreateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'MatchUpdateCreate'
} as const;

export const MatchUpdatePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'content', 'created_at'],
    title: 'MatchUpdatePublic'
} as const;

export const MatchUpdatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MatchUpdatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MatchUpdatesPublic'
} as const;

export const MatchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MatchPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MatchesPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlayerAdminSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        first_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'First Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        jersey_number: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 99,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Jersey Number'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        has_parental_consent: {
            type: 'boolean',
            title: 'Has Parental Consent',
            default: false
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        }
    },
    type: 'object',
    required: ['name', 'first_name', 'id'],
    title: 'PlayerAdmin',
    description: 'Admin view — all fields visible.'
} as const;

export const PlayerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        jersey_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Jersey Number'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        },
        has_full_profile: {
            type: 'boolean',
            title: 'Has Full Profile',
            default: false
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'first_name'],
    title: 'PlayerPublic',
    description: 'Public player — fields filtered based on consent.'
} as const;

export const PlayersAdminPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerAdmin'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersAdminPublic'
} as const;

export const PlayersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TeamContentPublicSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'TeamContentPublic'
} as const;

export const TeamContentUpdateSchema = {
    properties: {
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'TeamContentUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;