// This file is auto-generated by @hey-api/openapi-ts

export type Body_coaches_create_coach = {
    name: string;
    role: string;
    biography?: (string | null);
    sort_order?: number;
    photo?: ((Blob | File) | null);
};

export type Body_coaches_update_coach = {
    name?: (string | null);
    role?: (string | null);
    biography?: (string | null);
    sort_order?: (number | null);
    photo?: ((Blob | File) | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_match_media_upload_match_photo = {
    photo: (Blob | File);
    caption?: (string | null);
};

export type Body_players_create_player = {
    name: string;
    first_name: string;
    position?: (string | null);
    jersey_number?: (number | null);
    biography?: (string | null);
    has_parental_consent?: boolean;
    sort_order?: number;
    photo?: ((Blob | File) | null);
};

export type Body_players_update_player = {
    name?: (string | null);
    first_name?: (string | null);
    position?: (string | null);
    jersey_number?: (number | null);
    biography?: (string | null);
    has_parental_consent?: (boolean | null);
    sort_order?: (number | null);
    photo?: ((Blob | File) | null);
};

export type CoachesPublic = {
    data: Array<CoachPublic>;
    count: number;
};

export type CoachPublic = {
    name: string;
    role: string;
    biography?: (string | null);
    sort_order?: number;
    id: string;
    photo_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LandingPageData = {
    upcoming_matches: Array<MatchPublic>;
    recent_matches: Array<MatchPublic>;
    team_name: string;
};

export type MatchCreate = {
    match_date: string;
    home_team: string;
    away_team: string;
    precautions?: (string | null);
};

/**
 * Match detail including updates and media.
 */
export type MatchDetailPublic = {
    match_date: string;
    home_team: string;
    away_team: string;
    precautions?: (string | null);
    id: string;
    status: string;
    home_score?: (number | null);
    away_score?: (number | null);
    updates?: Array<MatchUpdatePublic>;
    media?: Array<MatchMediaPublic>;
};

export type MatchesPublic = {
    data: Array<MatchPublic>;
    count: number;
};

export type MatchMediaPublic = {
    id: string;
    media_type: string;
    file_path?: (string | null);
    url?: (string | null);
    caption?: (string | null);
    title?: (string | null);
    sort_order?: number;
};

export type MatchMediaVideoCreate = {
    url: string;
    title?: (string | null);
    caption?: (string | null);
};

/**
 * PATCH body for updating a match (named to avoid collision with MatchUpdate table).
 */
export type MatchPatch = {
    match_date?: (string | null);
    home_team?: (string | null);
    away_team?: (string | null);
    precautions?: (string | null);
    status?: (MatchStatus | null);
    home_score?: (number | null);
    away_score?: (number | null);
};

export type MatchPublic = {
    match_date: string;
    home_team: string;
    away_team: string;
    precautions?: (string | null);
    id: string;
    status: string;
    home_score?: (number | null);
    away_score?: (number | null);
};

export type MatchStatus = 'upcoming' | 'live' | 'completed';

export type MatchUpdateCreate = {
    content: string;
};

export type MatchUpdatePublic = {
    id: string;
    content: string;
    created_at: string;
};

export type MatchUpdatesPublic = {
    data: Array<MatchUpdatePublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Admin view — all fields visible.
 */
export type PlayerAdmin = {
    name: string;
    first_name: string;
    position?: (string | null);
    jersey_number?: (number | null);
    biography?: (string | null);
    has_parental_consent?: boolean;
    sort_order?: number;
    id: string;
    photo_url?: (string | null);
};

/**
 * Public player — fields filtered based on consent.
 */
export type PlayerPublic = {
    id: string;
    first_name: string;
    position?: (string | null);
    jersey_number?: (number | null);
    biography?: (string | null);
    photo_url?: (string | null);
    has_full_profile?: boolean;
    sort_order?: number;
};

export type PlayersAdminPublic = {
    data: Array<PlayerAdmin>;
    count: number;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TeamContentPublic = {
    content: string;
    updated_at?: (string | null);
};

export type TeamContentUpdate = {
    content: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CoachesListCoachesResponse = (CoachesPublic);

export type CoachesCreateCoachData = {
    formData: Body_coaches_create_coach;
};

export type CoachesCreateCoachResponse = (CoachPublic);

export type CoachesUpdateCoachData = {
    coachId: string;
    formData?: Body_coaches_update_coach;
};

export type CoachesUpdateCoachResponse = (CoachPublic);

export type CoachesDeleteCoachData = {
    coachId: string;
};

export type CoachesDeleteCoachResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MatchesCreateMatchData = {
    requestBody: MatchCreate;
};

export type MatchesCreateMatchResponse = (MatchPublic);

export type MatchesListMatchesData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type MatchesListMatchesResponse = (MatchesPublic);

export type MatchesUpdateMatchData = {
    matchId: string;
    requestBody: MatchPatch;
};

export type MatchesUpdateMatchResponse = (MatchPublic);

export type MatchesDeleteMatchData = {
    matchId: string;
};

export type MatchesDeleteMatchResponse = (Message);

export type MatchMediaUploadMatchPhotoData = {
    formData: Body_match_media_upload_match_photo;
    matchId: string;
};

export type MatchMediaUploadMatchPhotoResponse = (MatchMediaPublic);

export type MatchMediaAddMatchVideoLinkData = {
    matchId: string;
    requestBody: MatchMediaVideoCreate;
};

export type MatchMediaAddMatchVideoLinkResponse = (MatchMediaPublic);

export type MatchMediaDeleteMatchMediaData = {
    matchId: string;
    mediaId: string;
};

export type MatchMediaDeleteMatchMediaResponse = (Message);

export type MatchUpdatesCreateMatchUpdateData = {
    matchId: string;
    requestBody: MatchUpdateCreate;
};

export type MatchUpdatesCreateMatchUpdateResponse = (MatchUpdatePublic);

export type MatchUpdatesDeleteMatchUpdateData = {
    matchId: string;
    updateId: string;
};

export type MatchUpdatesDeleteMatchUpdateResponse = (Message);

export type PlayersListPlayersResponse = (PlayersAdminPublic);

export type PlayersCreatePlayerData = {
    formData: Body_players_create_player;
};

export type PlayersCreatePlayerResponse = (PlayerAdmin);

export type PlayersUpdatePlayerData = {
    formData?: Body_players_update_player;
    playerId: string;
};

export type PlayersUpdatePlayerResponse = (PlayerAdmin);

export type PlayersDeletePlayerData = {
    playerId: string;
};

export type PlayersDeletePlayerResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublicGetLandingPageResponse = (LandingPageData);

export type PublicGetTeamContentResponse = (TeamContentPublic);

export type PublicGetCoachesResponse = (CoachesPublic);

export type PublicGetPlayersResponse = (PlayersPublic);

export type PublicGetMatchesData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type PublicGetMatchesResponse = (MatchesPublic);

export type PublicGetMatchDetailData = {
    matchId: string;
};

export type PublicGetMatchDetailResponse = (MatchDetailPublic);

export type PublicGetMatchUpdatesData = {
    after?: (string | null);
    matchId: string;
};

export type PublicGetMatchUpdatesResponse = (MatchUpdatesPublic);

export type TeamContentGetTeamContentResponse = (TeamContentPublic);

export type TeamContentUpdateTeamContentData = {
    requestBody: TeamContentUpdate;
};

export type TeamContentUpdateTeamContentResponse = (TeamContentPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);